"""Stage 2 Step 18 — figures built ONLY from CONFIRMED published values.

No CheXpert file has been downloaded. Every number in this script is transcribed
from a primary source and carries its citation in `SOURCE` below; nothing is
assumed, estimated or fabricated. Values derived by arithmetic from those numbers
are labelled INFERRED on the figure itself.

Figures that need the actual CSV or image files are NOT produced here — they are
listed as DEFERRED in docs/dataset_analysis.md §18.1 and are generated by
analyze_metadata.py / validate_images.py once the data arrives.

Run:  python src/data/plot_published_stats.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))

from chexpert_metadata import (  # noqa: E402
    PALETTE,
    apply_plot_style,
    compact_formatter,
    ensure_dirs,
    load_config,
)

SOURCE_T1 = "Irvin et al. 2019 (arXiv:1901.07031), Table 1 — study level, n=187,641"
SOURCE_T3 = "Irvin et al. 2019, Table 3 — validation AUC, 200 studies"
SOURCE_DS = "Irvin et al. 2019 + CheXpert datasheet (arXiv:2105.03020)"

# --- CONFIRMED: Irvin et al. Table 1, study level -----------------------------
# (positive, uncertain, negative-including-no-mention)
TABLE1 = {
    "No Finding":                 (16_627, 0, 171_014),
    "Enlarged Cardiomediastinum": (9_020, 10_148, 168_473),
    "Cardiomegaly":               (23_002, 6_597, 158_042),
    "Lung Lesion":                (6_856, 1_071, 179_714),
    "Lung Opacity":               (92_669, 4_341, 90_631),
    "Edema":                      (48_905, 11_571, 127_165),
    "Consolidation":              (12_730, 23_976, 150_935),
    "Pneumonia":                  (4_576, 15_658, 167_407),
    "Atelectasis":                (29_333, 29_377, 128_931),
    "Pneumothorax":               (17_313, 2_663, 167_665),
    "Pleural Effusion":           (75_696, 9_419, 102_526),
    "Pleural Other":              (2_441, 1_771, 183_429),
    "Fracture":                   (7_270, 484, 179_887),
    "Support Devices":            (105_831, 898, 80_912),
}
N_STUDIES = 187_641

# --- CONFIRMED: Irvin et al. Table 3, Cardiomegaly column ---------------------
# policy -> (AUC, ci_low, ci_high)
TABLE3_CARDIOMEGALY = {
    "U-Ignore":       (0.828, 0.769, 0.888),
    "U-Ones":         (0.832, 0.773, 0.890),
    "U-SelfTrained":  (0.831, 0.770, 0.891),
    "U-Zeros":        (0.840, 0.783, 0.897),
    "U-MultiClass":   (0.854, 0.800, 0.909),
}
CHOSEN_POLICY = "U-Zeros"

# --- CONFIRMED: per-split composition ------------------------------------------
COMPOSITION = {           # split: (patients, studies, images)
    "train": (64_540, 187_641, 223_414),
    "valid": (200, 200, 234),
    "test":  (500, 500, 668),
}


def _caption(fig, text: str) -> None:
    fig.text(0.005, -0.02, text, fontsize=7.5, color=PALETTE["muted"], ha="left", va="top")


def _labels(ax, bars, values, fmt=lambda v: f"{v:,}", horizontal=True, pad=1.01):
    for bar, v in zip(bars, values):
        if horizontal:
            ax.text(bar.get_width() * pad, bar.get_y() + bar.get_height() / 2, fmt(v),
                    va="center", ha="left", fontsize=8.5, color=PALETTE["ink_secondary"])
        else:
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() * pad, fmt(v),
                    va="bottom", ha="center", fontsize=8.5, color=PALETTE["ink_secondary"])


# --- figure 1: Cardiomegaly label states ---------------------------------------
def fig_cardiomegaly_states(out: Path) -> None:
    pos, unc, neg = TABLE1["Cardiomegaly"]
    labels = ["Positive", "Negative\n(incl. no mention)", "Uncertain"]
    values = [pos, neg, unc]
    colors = [PALETTE["series_2"], PALETTE["series_1"], PALETTE["series_3"]]

    fig, ax = plt.subplots(figsize=(7.6, 2.9))
    bars = ax.barh(labels[::-1], values[::-1], color=colors[::-1], height=0.6)
    ax.set_title("Cardiomegaly label states — CONFIRMED, study level")
    ax.set_xlim(0, max(values) * 1.32)
    ax.xaxis.set_visible(False)
    ax.grid(False)
    ax.spines["bottom"].set_visible(False)
    _labels(ax, bars, values[::-1],
            fmt=lambda v: f"{v:,}   ({100 * v / N_STUDIES:.2f}%)")
    _caption(fig, f"CONFIRMED · {SOURCE_T1}. Image-level counts require train.csv — DEFERRED.")
    fig.tight_layout()
    fig.savefig(out / "01_cardiomegaly_label_states.png", bbox_inches="tight")
    plt.close(fig)


# --- figure 2: uncertainty rate across all 14 observations ---------------------
def fig_uncertainty_rates(out: Path) -> None:
    names = list(TABLE1)
    rates = [100 * TABLE1[n][1] / N_STUDIES for n in names]
    order = np.argsort(rates)
    names = [names[i] for i in order]
    rates = [rates[i] for i in order]
    colors = [PALETTE["series_2"] if n == "Cardiomegaly" else PALETTE["muted"] for n in names]

    fig, ax = plt.subplots(figsize=(7.8, 5.0))
    bars = ax.barh(names, rates, color=colors, height=0.66)
    ax.set_title("Uncertain-label rate by observation — Cardiomegaly is among the lowest")
    ax.set_xlim(0, max(rates) * 1.22)
    ax.xaxis.set_visible(False)
    ax.grid(False)
    ax.spines["bottom"].set_visible(False)
    for lbl in ax.get_yticklabels():
        if lbl.get_text() == "Cardiomegaly":
            lbl.set_color(PALETTE["ink"])
            lbl.set_fontweight("bold")
    _labels(ax, bars, rates, fmt=lambda v: f"{v:.2f}%")
    _caption(fig, f"CONFIRMED · {SOURCE_T1}. Supports D203: the uncertainty policy moves "
                  f"only 3.52% of Cardiomegaly studies.")
    fig.tight_layout()
    fig.savefig(out / "02_uncertainty_rate_by_observation.png", bbox_inches="tight")
    plt.close(fig)


# --- figure 3: policy AUC with confidence intervals ----------------------------
def fig_policy_auc(out: Path) -> None:
    """Point estimates with intervals -> dot plot with error bars, sorted by AUC."""
    items = sorted(TABLE3_CARDIOMEGALY.items(), key=lambda kv: kv[1][0])
    names = [k for k, _ in items]
    auc = np.array([v[0] for _, v in items])
    lo = np.array([v[1] for _, v in items])
    hi = np.array([v[2] for _, v in items])
    y = np.arange(len(names))
    colors = [PALETTE["series_2"] if n == CHOSEN_POLICY else PALETTE["series_1"] for n in names]

    fig, ax = plt.subplots(figsize=(7.8, 3.4))
    for i in range(len(names)):
        ax.plot([lo[i], hi[i]], [y[i], y[i]], color=colors[i], linewidth=2, alpha=0.45,
                solid_capstyle="round")
        ax.plot(auc[i], y[i], "o", color=colors[i], markersize=9,
                markeredgecolor=PALETTE["surface"], markeredgewidth=2, zorder=3)
        ax.text(hi[i] + 0.004, y[i], f"{auc[i]:.3f}", va="center", fontsize=8.5,
                color=PALETTE["ink_secondary"])
    ax.set_yticks(y, names)
    for lbl, n in zip(ax.get_yticklabels(), names):
        if n == CHOSEN_POLICY:
            lbl.set_color(PALETTE["ink"]); lbl.set_fontweight("bold")
    ax.set_title("Cardiomegaly validation AUC by uncertainty policy — 95% CIs overlap")
    ax.set_xlabel("AUROC (bar = 95% CI)")
    ax.set_xlim(0.75, 0.945)
    ax.grid(axis="y", visible=False)
    _caption(fig, f"CONFIRMED · {SOURCE_T3}. Orange = our choice (D203). U-MultiClass's "
                  f"higher point estimate sits inside every other interval.")
    fig.tight_layout()
    fig.savefig(out / "03_uncertainty_policy_auc.png", bbox_inches="tight")
    plt.close(fig)


# --- figure 4: projected class balance under each policy -----------------------
def fig_policy_balance(out: Path) -> None:
    """INFERRED — arithmetic on Table 1, at STUDY level only."""
    pos, unc, neg = TABLE1["Cardiomegaly"]
    policies = ["U-Zeros", "U-Ones", "Exclusion"]
    p_counts = [pos, pos + unc, pos]
    n_counts = [neg + unc, neg, neg]

    x = np.arange(len(policies))
    w = 0.36
    fig, ax = plt.subplots(figsize=(7.4, 3.6))
    b1 = ax.bar(x - w / 2, p_counts, w, label="Positive", color=PALETTE["series_2"])
    b2 = ax.bar(x + w / 2, n_counts, w, label="Negative", color=PALETTE["series_1"])
    ax.set_xticks(x, policies)
    ax.set_title("Class balance by uncertainty policy — INFERRED, study level")
    ax.set_ylim(0, max(n_counts) * 1.20)
    ax.yaxis.set_visible(False)
    ax.grid(False)
    ax.spines["left"].set_visible(False)
    ax.legend(loc="upper left", fontsize=9)
    for bars, vals in ((b1, p_counts), (b2, n_counts)):
        _labels(ax, bars, vals, horizontal=False)
    for i, (p, n) in enumerate(zip(p_counts, n_counts)):
        ax.text(i, -max(n_counts) * 0.07, f"{100 * p / (p + n):.2f}% positive",
                ha="center", fontsize=8.5, color=PALETTE["muted"])
    _caption(fig, "INFERRED by arithmetic from Table 1. Frontal-only IMAGE-level counts "
                  "require train.csv — DEFERRED (see §6.3).")
    fig.tight_layout()
    fig.savefig(out / "04_uncertainty_policy_balance.png", bbox_inches="tight")
    plt.close(fig)


# --- figure 5: official split composition --------------------------------------
def fig_composition(out: Path) -> None:
    """Counts spanning three orders of magnitude (200 -> 223,414).

    A linear bar chart renders valid and test as nothing at all, and bars on a log
    axis are an anti-pattern (bar length must be zero-anchored to mean anything).
    A dot plot encodes value by POSITION, so a log axis is legitimate — and it is
    the only form that shows both the composition and the scale gap at once.
    """
    splits = list(COMPOSITION)[::-1]
    measures = ["patients", "studies", "images"]
    colors = [PALETTE["series_1"], PALETTE["series_2"], PALETTE["series_3"]]
    y = np.arange(len(splits))
    offs = [0.22, 0.0, -0.22]

    fig, ax = plt.subplots(figsize=(8.4, 3.2))
    for mi, (measure, color, off) in enumerate(zip(measures, colors, offs)):
        vals = [COMPOSITION[s][mi] for s in splits]
        ax.scatter(vals, y + off, s=78, color=color, label=measure,
                   edgecolor=PALETTE["surface"], linewidth=1.6, zorder=3)
        for v, yy in zip(vals, y + off):
            ax.text(v * 1.18, yy, f"{v:,}", va="center", fontsize=8.5,
                    color=PALETTE["ink_secondary"])

    ax.set_xscale("log")
    ax.set_xlim(90, 1_400_000)
    ax.set_yticks(y, splits)
    ax.set_ylim(-0.55, len(splits) - 0.45)
    ax.set_title("Official CheXpert split composition (log scale)")
    ax.set_xlabel("count — log scale")
    ax.grid(axis="y", visible=False)
    # Below the axis, not inside it — in the plot area a 3-dot legend reads as a
    # fourth data row.
    ax.legend(fontsize=9, ncol=3, loc="upper center", bbox_to_anchor=(0.5, -0.28))
    _caption(fig, f"CONFIRMED · {SOURCE_DS}. Log scale because the range spans 3 orders of "
                  f"magnitude. valid+test are 0.4% of images yet carry the ONLY "
                  f"radiologist-verified labels — the asymmetry behind D205.")
    fig.tight_layout()
    fig.savefig(out / "05_official_split_composition.png", bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    cfg = load_config()
    ensure_dirs(cfg)
    apply_plot_style()
    out = Path(cfg["paths"]["figures"])
    out.mkdir(parents=True, exist_ok=True)

    fig_cardiomegaly_states(out)
    fig_uncertainty_rates(out)
    fig_policy_auc(out)
    fig_policy_balance(out)
    fig_composition(out)

    print(f"[ok] 5 published-value figures -> {out}")
    print("     DEFERRED until data lands: view distribution, label-by-view, "
          "image dimensions, example images.")


if __name__ == "__main__":
    main()
